### ISSUE TITLE
Mobile Match Data Rendering

### ISSUE THREAD

**Issue by Autumn-Ou** [scoutmachine/web#19]
**Describe the bug**
Unusable UI

**To Reproduce**
1. Load team page
2. Pick season
3. Scroll down

**Screenshots**
![image](https://github.com/gryphonmachine/machine/assets/62668093/5c7d7120-b4d0-4e76-82ca-36f4ea7675b5)

**Browser**
- OS: iOS
- Browser: chrome

**Additional context**
None

**Comment by heybereket** [comment]
New UI for this - closing.
