### ISSUE TITLE
Verifying Team Members & Access

### ISSUE THREAD

**Issue by eternalmoon1234** [scoutmachine/web#23]
**Verifying Team Members & Access**

Need to add a standardized system to authorize users to edit a team page, as well as a way to mark users as members, mentors, alumni, etc.

**Comment by eternalmoon1234** [comment]
In the meantime, we could consider manually verifying users, but we should find a more sophisticated solution in the long run.

**Comment by Autumn-Ou** [comment]
> In the meantime, we could consider manually verifying users, but we should find a more sophisticated solution in the long run.

You might have to stick to manual verification unless you can API call with FIRST to check team codes that get given to coaches, but I believe TBA got special access to do that, maybe making a standardized form for users to submit right now is a good intermediate solution.
