### ISSUE TITLE
Menu Button Render vs Interactable

### ISSUE THREAD

**Issue by Autumn-Ou** [scoutmachine/web#36]
**Describe the bug**
Menu button is not interactable for its full size, left side past white bars does not trigger.

**To Reproduce**

1. Open left of the white bars

**Screenshots**
![image](https://github.com/scoutmachine/web/assets/62668093/b3f0f733-9d63-4c39-8472-880cbe074cdd)

**Browser**

- OS: Windows 11
- Browser: Edge *Chromium Backend*

**Additional context**
Makes UI interactions clunky since implied whole button will interact but does not.

**Comment by heybereket** [comment]
Fixed as of e12531c05e957314ff677f0b24ec2ad62662345b.
