### ISSUE TITLE
Image & Text Clipping in Teams Panel

### ISSUE THREAD

**Issue by Autumn-Ou** [scoutmachine/web#37]
**Describe the bug**
Image clips with text inside team panel, also occurs in wider panels when teams have longer names.

**Steps To Reproduce**
Narrow ish panels for favourited teams on main page

**Screenshots**
![image](https://github.com/scoutmachine/web/assets/62668093/bc2fce42-94ea-4d3b-abdd-ec9c469cae2e)

**Browser**
- OS: Windows 11
- Browser: Edge *Chromium Backend*

**Additional context**
Just need a better way to render text and the logo.

**Comment by heybereket** [comment]
Seems to not be occurring any longer. Closing issue for now.
